server.port=8081

spring.application.name=api-gateway

# Route 1: Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:9000
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Route 2: Cloud Core
spring.cloud.gateway.routes[1].id=cloud-core
spring.cloud.gateway.routes[1].uri=http://localhost:9001
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**

# Route 3: WebSockets
spring.cloud.gateway.routes[2].id=cloud-ws
spring.cloud.gateway.routes[2].uri=ws://localhost:9001
spring.cloud.gateway.routes[2].predicates[0]=Path=/ws/**