# --- Server Configuration ---
# Runs this service on port 8081 to avoid conflict with Core API (8080)
server.port=8082

# --- Application Metadata ---
spring.application.name=cloud-orchestrator

# --- Logging Configuration ---
# Keep logs clean, but show INFO for our app
logging.level.root=INFO
# Docker Java can be very chatty, let's keep it to WARN unless debugging
logging.level.com.github.dockerjava=WARN